#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Module-Extract
Version  : 0.01
Release  : 12
URL      : https://cpan.metacpan.org/authors/id/A/AD/ADAMK/Module-Extract-0.01.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/A/AD/ADAMK/Module-Extract-0.01.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libm/libmodule-extract-perl/libmodule-extract-perl_0.01-2.debian.tar.xz
Summary  : Base class for working with Perl distributions
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-2.0
BuildRequires : buildreq-cpan
BuildRequires : perl(Archive::Extract)
BuildRequires : perl(Module::Install)

%description
NAME
Module::Extract - Base class for working with Perl distributions
SYNOPSIS
Creating a Module::Extract subclass.

%prep
%setup -q -n Module-Extract-0.01
cd ..
%setup -q -T -D -n Module-Extract-0.01 -b 1
mkdir -p deblicense/
cp -r %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Module-Extract-0.01/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Module-Extract
cp LICENSE %{buildroot}/usr/share/package-licenses/perl-Module-Extract/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
