#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Module-Extract
Version  : 0.01
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/A/AD/ADAMK/Module-Extract-0.01.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/A/AD/ADAMK/Module-Extract-0.01.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libm/libmodule-extract-perl/libmodule-extract-perl_0.01-2.debian.tar.xz
Summary  : Base class for working with Perl distributions
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-2.0
Requires: perl-Module-Extract-license
Requires: perl-Module-Extract-man
Requires: perl(Archive::Extract)
Requires: perl(Module::Install)
BuildRequires : perl(Archive::Extract)
BuildRequires : perl(Module::Install)

%description
NAME
Module::Extract - Base class for working with Perl distributions
SYNOPSIS
Creating a Module::Extract subclass.

%package license
Summary: license components for the perl-Module-Extract package.
Group: Default

%description license
license components for the perl-Module-Extract package.


%package man
Summary: man components for the perl-Module-Extract package.
Group: Default

%description man
man components for the perl-Module-Extract package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Module-Extract-0.01
mkdir -p %{_topdir}/BUILD/Module-Extract-0.01/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Module-Extract-0.01/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Module-Extract
cp LICENSE %{buildroot}/usr/share/doc/perl-Module-Extract/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Module/Extract.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Module-Extract/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Module::Extract.3
